### ISSUE TITLE
Failed to open file descriptor 

### ISSUE THREAD

**Issue by AhmedSoliman3** [kimsniper/ros2_mpu6050#1]
$ ros2 run ros2_mpu6050 ros2_mpu6050_calibrate
Failed to open file descriptor!
[ros2run]: Process exited with failure 1

also 

$ ros2 launch ros2_mpu6050 ros2_mpu6050.launch.py
[INFO] [launch]: All log files can be found below /home/amr/.ros/log/2024-10-18-16-50-53-341707-amr-desktop-3178
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ros2_mpu6050-1]: process started with pid [3179]
[ros2_mpu6050-1] Failed to open file descriptor!
[ERROR] [ros2_mpu6050-1]: process has died [pid 3179, exit code 1, cmd '/home/amr/ros2_ws/install/ros2_mpu6050/lib/ros2_mpu6050/ros2_mpu6050 --ros-args -r __node:=mpu6050_sensor --params-file /home/amr/ros2_ws/install/ros2_mpu6050/share/ros2_mpu6050/config/params.yaml'].

while :$ ls /dev/i2c-*
/dev/i2c-0  /dev/i2c-1  /dev/i2c-10  /dev/i2c-20  /dev/i2c-21  /dev/i2c-22
 and 
$ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --   
I don't know what's wrong 
I'm using ubuntu 22.04 over Raspberry pi 4 with humble ros2 version

**Comment by AhmedSoliman3** [comment]
i found this solve the problem $sudo chmod 666 /dev/i2c-1

**Comment by kimsniper** [comment]
Hi @AhmedSoliman3 , yep it was a permission issue, I'm glad you made it work. Please don't forget to close the issue if everything worked well. Thanks
